### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by LucidAPs** [Ajneb97/ConditionalEvents#14] opened 2023-03-13 16:54 UTC
The item_interact event is allocating a lot of memory.
https://spark.lucko.me/05pLHwyAsQ

**Comment by Ajneb97** [comment] 2023-03-13 17:26
How many item_interact and block_interact events do you have? It seems the memory issue is caused by the MathUtils.calculate() method, which tries to parse formulas in conditions.

**Comment by LucidAPs** [comment] 2023-03-13 17:28
> 

These are all the item_interact events I am using
https://nekobin.com/miwuzoyefe

**Comment by Ajneb97** [comment] 2023-03-14 01:05
Ok I will check it on my server

**Comment by Ajneb97** [comment] 2023-06-05 01:06
This should be fixed now.

**Closed by Ajneb97** 2023-06-05 01:06 UTC
